---
# AWS Organizations policy examples
files:
  - path: organizations_policies.py
    services:
      - organizations
  - path: test/test_organizations_policies.py
    services:
      - organizations
  - path: test/conftest.py
    services:
      - organizations
...
