---
# Amazon DynamoDB getting started examples
files:
  - path: GettingStarted/MoviesCreateTable.py
    services:
      - dynamodb
  - path: GettingStarted/MoviesDeleteTable.py
    services:
      - dynamodb
  - path: GettingStarted/MoviesItemOps01.py
    services:
      - dynamodb
  - path: GettingStarted/MoviesItemOps02.py
    services:
      - dynamodb
  - path: GettingStarted/MoviesItemOps03.py
    services:
      - dynamodb
  - path: GettingStarted/MoviesItemOps03a.py
    services:
      - dynamodb
  - path: GettingStarted/MoviesItemOps04.py
    services:
      - dynamodb
  - path: GettingStarted/MoviesItemOps05.py
    services:
      - dynamodb
  - path: GettingStarted/MoviesItemOps06.py
    services:
      - dynamodb
  - path: GettingStarted/MoviesListTables.py
    services:
      - dynamodb
  - path: GettingStarted/MoviesLoadData.py
    services:
      - dynamodb
  - path: GettingStarted/MoviesQuery01.py
    services:
      - dynamodb
  - path: GettingStarted/MoviesQuery02.py
    services:
      - dynamodb
  - path: GettingStarted/MoviesScan.py
    services:
      - dynamodb
  - path: GettingStarted/test/conftest.py
    services:
      - dynamodb
  - path: GettingStarted/test/test_dynamodb_getting_started.py
    services:
      - dynamodb
...
---
# Amazon DynamoDB Accelerator (DAX) examples
files:
  - path: TryDax/01-create-table.py
    services:
      - dynamodb
  - path: TryDax/02-write-data.py
    services:
      - dynamodb
  - path: TryDax/03-getitem-test.py
    services:
      - dynamodb
  - path: TryDax/04-query-test.py
    services:
      - dynamodb
  - path: TryDax/05-scan-test.py
    services:
      - dynamodb
  - path: TryDax/06-delete-table.py
    services:
      - dynamodb
  - path: TryDax/test/conftest.py
    services:
      - dynamodb
  - path: TryDax/test/test_try_dax.py
    services:
      - dynamodb
...
---
# Amazon DynamoDB batching examples
files:
  - path: batching/dynamo_batching.py
    services:
      - dynamodb
  - path: batching/test/conftest.py
    services:
      - dynamodb
  - path: batching/test/test_dynamo_batching.py
    services:
      - dynamodb
...