---
# AWS Security Token Service (AWS STS) examples
files:
  - path: sts_temporary_credentials/assume_role.py
    services:
      - iam
      - sts
  - path: sts_temporary_credentials/assume_role_mfa.py
    services:
      - iam
      - sts
  - path: sts_temporary_credentials/federated_url.py
    services:
      - iam
      - sts
  - path: sts_temporary_credentials/session_token.py
    services:
      - iam
      - sts
  - path: sts_temporary_credentials/test/conftest.py
    services:
      - iam
      - sts
  - path: sts_temporary_credentials/test/test_assume_role.py
    services:
      - iam
      - sts
  - path: sts_temporary_credentials/test/test_assume_role_mfa.py
    services:
      - iam
      - sts
  - path: sts_temporary_credentials/test/test_federated_url.py
    services:
      - iam
      - sts
  - path: sts_temporary_credentials/test/test_session_token.py
    services:
      - iam
      - sts
...
