---
# Amazon Elastic Compute Cloud (EC2) basic usage examples
files:
  - path: ec2_basics/ec2_basics_demo.py
    services:
      - ec2
      - ssm
  - path: ec2_basics/ec2_instance_management.py
    services:
      - ec2
  - path: ec2_basics/ec2_setup.py
    services:
      - ec2
  - path: ec2_basics/ec2_teardown.py
    services:
      - ec2
  - path: ec2_basics/test/conftest.py
    services:
      - ec2
  - path: ec2_basics/test/test_ec2_instance_management.py
    services:
      - ec2
  - path: ec2_basics/test/test_ec2_setup.py
    services:
      - ec2
  - path: ec2_basics/test/test_ec2_teardown.py
    services:
      - ec2
...
