AWSTemplateFormatVersion: '2010-09-09'
Description: Example REST API with a usage plan, custom throttling, and an API key.
Resources:
  MyAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: example-with-usage-plan
  PetsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt
        - MyAPI
        - RootResourceId
      PathPart: pets
      RestApiId: !Ref MyAPI
  Method:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId: !Ref PetsResource
      RestApiId: !Ref MyAPI
      AuthorizationType: NONE
      Integration:
        Type: HTTP_PROXY
        Uri: http://petstore.execute-api.us-west-1.amazonaws.com/petstore/pets
        IntegrationHttpMethod: GET
  Deployment:
    DependsOn: Method
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref MyAPI
      StageName: tempstage
  TestStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: test
      RestApiId: !Ref MyAPI
      DeploymentId: !Ref Deployment
      Description: "test stage description"
  MyUsagePlan:
    DependsOn: TestStage
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: ExampleUsagePlan
      ApiStages:
        - ApiId: !Ref MyAPI
          Stage: test
          Throttle:
            "/pets/GET":
              BurstLimit: 100
              RateLimit: 100.0
      Throttle:
        BurstLimit: 200
        RateLimit: 200.0
  MyUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref MyAPIKey
      KeyType: API_KEY
      UsagePlanId: !Ref MyUsagePlan
  MyAPIKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Enabled: True

Outputs:
  InvokeURL:
    Value: !Sub https://${MyAPI}.execute-api.${AWS::Region}.amazonaws.com/test
