---
# Basic Amazon EMR examples
files:
  - path: emrfs_step.py
    services:
      - emr
  - path: emr_basics.py
    services:
      - emr
  - path: emr_usage_demo.py
    services:
      - emr
  - path: install_libraries.py
    services:
      - emr
      - ssm
  - path: pyspark_estimate_pi.py
    services:
      - emr
  - path: pyspark_top_product_keyword.py
    services:
      - emr
  - path: test/conftest.py
    services:
      - emr
  - path: test/test_emrfs_step.py
    services:
      - emr
  - path: test/test_emr_basics.py
    services:
      - emr
  - path: test/test_emr_usage_demo.py
    services:
      - emr
  - path: test/test_install_libraries.py
    services:
      - emr
      - ssm
...
