---
# Basic AWS Identity and Access Management (IAM) examples
files:
  - path: iam_basics/access_key_wrapper.py
    services:
      - iam
  - path: iam_basics/account_wrapper.py
    services:
      - iam
  - path: iam_basics/policy_wrapper.py
    services:
      - iam
  - path: iam_basics/role_wrapper.py
    services:
      - iam
  - path: iam_basics/user_wrapper.py
    services:
      - iam
  - path: iam_basics/test/conftest.py
    services:
      - iam
  - path: iam_basics/test/test_access_key_wrapper.py
    services:
      - iam
  - path: iam_basics/test/test_account_wrapper.py
    services:
      - iam
  - path: iam_basics/test/test_policy_wrapper.py
    services:
      - iam
  - path: iam_basics/test/test_role_wrapper.py
    services:
      - iam
  - path: iam_basics/test/test_user_wrapper.py
    services:
      - iam
...
