---
# Amazon Transcribe custom vocabulary example.
files:
  - path: transcribe_basics.py
    services:
      - transcribe
  - path: test/conftest.py
    services:
      - transcribe
  - path: test/test_transcribe_basics.py
    services:
      - transcribe
...
---
# Amazon Transcribe getting started example.
files:
  - path: getting_started.py
    services:
      - transcribe
  - path: test/test_transcribe_getting_started.py
    services:
      - transcribe
...