AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates a 'GetPosts' function in AWS Lambda."
Parameters:
  S3BucketName:
    Description: "Name of the Amazon S3 bucket that contains the 'GetPosts.zip' file you must upload for this function."
    Type: "String"
  IAMRoleARN:
    Description: "Amazon Resource Name (ARN) of the 'LambdaChatAppRole' role you create in IAM for this function to use."
    Type: "String"
Resources:
  DeleteCognitoUserFunction:
    Type: "AWS::Lambda::Function"
    Properties: 
      Code: 
        S3Bucket: 
          Ref: "S3BucketName"
        S3Key: "GetPosts.zip"
      Description: "Gets posts from the 'Posts' table in Amazon DynamoDB."
      FunctionName: "GetPosts"
      Handler: "index.handler"
      Role:
        Ref: "IAMRoleARN"
      Runtime: "nodejs6.10"
      Timeout: "30"