AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates a 'Posts' table in Amazon DynamoDB, with two attributes: 'Alias' (the partition key) and 'Timestamp' (the sort key)."
Resources:
  PostsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: "Alias"
          AttributeType: "S"
        - 
          AttributeName: "Timestamp"
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: "Alias"
          KeyType: "HASH"
        - 
          AttributeName: "Timestamp"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "Posts"
