AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates a 'ChatRoomPool' user pool in Amazon Cognito. Also adds a client named 'Chat-Room' to the user pool."
Resources:
  ChatRoomPoolUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties: 
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: "false"
      AutoVerifiedAttributes: 
        - 
          "email"
      Policies: 
        PasswordPolicy:
          MinimumLength: "6"
          RequireNumbers: "true"
      UserPoolName: "ChatRoomPool"
      Schema:
        - 
          AttributeDataType: "String"
          Name: "email"
          Required: "true"
  ChatRoomUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: "Chat-Room"
      ExplicitAuthFlows: 
        - 
          "ADMIN_NO_SRP_AUTH"
      RefreshTokenValidity: "30"
      UserPoolId: !Ref ChatRoomPoolUserPool
Outputs:
  UserPoolClientID:
    Description: "The client ID of the user pool that is created."
    Value: !Ref ChatRoomUserPoolClient
  UserPoolID:
    Description: "The ID of the user pool that is created."
    Value: !Ref ChatRoomPoolUserPool
  UserPoolIDShortURL:
    Description: "The URL prefix to the JWT Set for the user pool that is created."
    Value: !Join [ "", [ "https://cognito-idp.", !Ref "AWS::Region", ".amazonaws.com/", !Ref ChatRoomPoolUserPool ] ]
  UserPoolIDLongURL: 
    Description: "The URL to the JWT Set for the user pool that is created."
    Value: !Join [ "", [ "https://cognito-idp.", !Ref "AWS::Region", ".amazonaws.com/", !Ref ChatRoomPoolUserPool, "/.well-known/jwks.json" ] ]