###################################################################################################
#### Copyright 2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
####
#### Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file
#### except in compliance with the License. A copy of the License is located at
####
####     http://aws.amazon.com/apache2.0/
####
#### or in the "license" file accompanying this file. This file is distributed on an "AS IS"
#### BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#### License for the specific language governing permissions and limitations under the License.
###################################################################################################

###################################################################################################
#### When you run multiple applications with Elastic Beanstalk, it is a good practice to have
#### separate instance profiles for each application. The AWSElasticBeanstalkWebTier managed policy
#### gives the instance permission to use platform features that upload logs and performance data
#### to Amazon S3, AWS CloudWatch, and AWS X-Ray.
####
#### If you use the AWS SDK to access other services from your instances, add policies for those
#### services to the list of managed policies attached to the role. For example-
####
####        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
####        - "arn:aws:iam::aws:policy/AmazonSNSFullAccess"
####        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
####
#### If you use the Multicontainer Docker platform, add ECS and ECR permissios with these policies-
####
####        - "arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker"
####        - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
####
###################################################################################################

Resources:
  InstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier"
      RoleName: "beanstalk-web-instanceprofile-role"
  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref 'InstanceProfileRole'
      InstanceProfileName: "beanstalk-web-instanceprofile"
