---
# Learn how to create, get, and delete queues and send, receive, and delete messages.
files:
  - path: queue_wrapper.py
    services:
      - sqs
  - path: message_wrapper.py
    services:
      - sqs
  - path: test/conftest.py
  - path: test/test_message_wrapper.py
  - path: test/test_queue_wrapper.py
...